---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione di NetApp XCP
    url: "/index.html"
  - title: Note di rilascio
    url: "/releasenotes.html"
  - title: Inizia a utilizzare XCP
    type: solutions
    entries:
    - title: Scopri XCP
      url: "/xcp-index.html"
    - title: Funzionalità add-on NFS XCP
      url: "/xcp-nfs-add-ons.html"
    - title: Funzionalità non supportate
      url: "/xcp-unsupported-features.html"
    - title: Configurazioni supportate
      url: "/xcp-supported-configurations.html"
    - title: Porte utilizzate da XCP
      url: "/xcp-ports-used.html"
  - title: Installare XCP
    entries:
    - title: Preparazione per l'installazione di XCP
      url: "/xcp-install-xcp.html"
    - title: Preparare Linux per XCP NFS
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: Preparare Windows per XCP SMB
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: Preparazione di file Analytics
      url: "/xcp-prepare-file-analytics.html"
    - title: Installare XCP NFS
      url: "/xcp-install-xcp-nfs.html"
    - title: Installare XCP SMB
      url: "/xcp-install-xcp-smb.html"
    - title: Installare file Analytics per NFS
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: Installare file Analytics per SMB
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: Configurare XCP
    entries:
    - title: Configurare il file INI per XCP NFS
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: Tuning delle performance
      url: "/xcp-performance-tuning.html"
    - title: Variabile di ambiente
      url: "/xcp-environment-variable.html"
    - title: Configurare il connettore POSIX
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: Configurare il connettore HDFS
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: Configurare lo scale-out multinodo
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: Configurare il connettore S3
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: Pianificare la migrazione dei dati
    url: "/xcp-plan-data-migration.html"
    entries:
    - title: Pianificare la migrazione dei dati NFS
      url: "/xcp-plan-nfs-data-migration.html"
    - title: Pianificare la migrazione dei dati SMB
      url: "/xcp-plan-smb-data-migration.html"
    - title: Pianificare la migrazione dei dati HDFS
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: Pianificare utilizzando file Analytics
      entries:
      - title: Pianifica la migrazione dei dati
        url: "/xcp-file-analytics-plan-data-migration.html"
      - title: Accedere a file Analytics
        url: "/xcp-access-file-analytics.html"
      - title: Aggiungere file server
        url: "/xcp-add-file-servers.html"
      - title: Eseguire una scansione
        url: "/xcp-run-a-scan.html"
    - title: Filtri
      url: "/xcp-filters.html"
    - title: Registrazione per NFS e SMB (opzionale)
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: Migrare i dati
    entries:
    - title: Migrare i dati NFS
      url: "/xcp-migrate-data.html"
    - title: Migrare i dati delle PMI
      url: "/xcp-migrate-smb-data.html"
      entries:
      - title: Migrazione di flussi di dati alternativi NTFS per SMB
        url: "/xcp-smb-ads.html"
    - title: Migrare i dati HDFS
      url: "/xcp-migrate-hdfs-data.html"
    - title: Eseguire più lavori XCP sullo stesso host
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: Funzionalità NFS aggiuntive
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: Risolvere i problemi
    entries:
    - title: Risolvere i problemi relativi agli errori NFS XCP
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: Risolvere gli errori SMB XCP
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: Risolvere gli errori di XCP file Analytics
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: Note legali
    url: "/legal-notices.html"
