---
sidebar: sidebar 
permalink: xcp-nfs-reference-estimate.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Riferimento comando NFS XCP 
---
= stima
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il NFS di XCP `estimate` il comando viene utilizzato per stimare il tempo necessario per completare una copia di base dall'origine alla destinazione. Calcola il tempo stimato per completare una copia di base utilizzando tutte le risorse di sistema disponibili correnti, come CPU, RAM, rete e altri parametri. È possibile utilizzare `-target` opzione per avviare un'operazione di copia di esempio e ottenere il tempo di stima.

.Sintassi
[source, cli]
----
xcp estimate -id <name>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.10.10:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.10.10:/temp4' to
'10.101.10.10:/temp8'...
estimate regular file copy task completed before the 1m40s duration
0 in (0/s), 0 out (0/s), 5s
0 in (0/s), 0 out (0/s), 10s
Estimated time to copy '10.101.12.11:/temp4' to '10.101.12.10:/temp8' based on a 1m40s live test:
5.3s
Xcp command : xcp estimate -t 100 -id estimate01 -target 10.101.12.10:/temp8
Estimated Time : 5.3s
Job ID : Job_2023-04-12_08.09.16.126908_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====
La seguente tabella elenca `estimate` parametri e loro descrizione.

[cols="2*"]
|===
| Parametro | Descrizione 


| <<nfs_estimate_id,stima -id   >> | Specifica il nome di catalogo di un indice di copia o scansione precedente. 


| <<nfs_estimate_gbit,stima -gbit   >> | Utilizza i gigabyte di larghezza di banda per stimare il tempo del caso migliore (default: 1). 


| <<nfs_estimate_target,stima -target   >> | Specifica la destinazione da utilizzare per la copia di prova in tempo reale. 


| <<nfs_estimate_t,stima -t /s/m/h]>  | Specifica la durata della copia di prova in tempo reale (impostazione predefinita: 5m). 


| <<nfs_estimate_bs,stima -bs [k]>  | Specifica le dimensioni del blocco di lettura/scrittura (valore predefinito: 64K). 


| <<nfs_estimate_dircount,stima -dircount [k]>   | Specifica la dimensione della richiesta per la lettura delle directory (valore predefinito: 64K). 


| <<nfs_estimate_preserveatime,stima -preserva-atime >> | Preserva i tempi di accesso del file o della directory (default: False). 


| <<nfs_estimate_loglevel,stima -loglevel  >> | Consente di impostare il livello di registro; i livelli disponibili sono INFO, DEBUG (valore predefinito: INFO) 
|===


== stima -id <name>

Utilizzare `-id <name>` con il `estimate` comando per escludere i file e le directory che corrispondono al filtro.

.Sintassi
[source, cli]
----
xcp estimate -id <name>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id csdata01

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 62.0 MiB free space.
Job ID: Job_2023-04-20_12.59.31.260914_estimate
== Best-case estimate to copy ‘data-set:/user1given 1 gigabit of bandwidth ==
112 TiB of data at max 128 MiB/s: at least 10d13h
Xcp command : xcp estimate -id csdata01
Estimated Time : 10d13h
Job ID : Job_2023-04-20_12.59.31.260914_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_12.59.31.260914_estimate.log
STATUS : PASSED
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 62.0 MiB free space.
[root@client1 linux]#
----
====


== stima -gbit <n>

Utilizzare `-gbit <n>` con il `estimate` comando per stimare il tempo dei casi migliori (default: 1). Questa opzione non può essere utilizzata con `-target` opzione.

.Sintassi
[source, cli]
----
xcp estimate -gbit <n> -id <name>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -gbit 10 -id estimate01

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-12_08.12.28.453735_estimate
== Best-case estimate to copy '10.101.12.11:/temp4' given 10 gigabits of bandwidth ==
0 of data at max 1.25 GiB/s: at least 0.0s
Xcp command : xcp estimate -gbit 10 -id estimate01
Estimated Time : 0.0s
Job ID : Job_2023-04-12_08.12.28.453735_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.12.28.453735_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== stima - <path> target

Utilizzare `-target <path>` con il `estimate` comando per specificare la destinazione da utilizzare per la copia di prova in tempo reale.

.Sintassi
[source, cli]
----
xcp estimate -t 100 -id <name> -target <path>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.12.11:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.12.11:/temp4' to '10.101.12.11:/temp8'...
estimate regular file copy task completed before the 1m40s duration
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== stima -t <n[s|m|h]>

Utilizzare `-t <n[s|m|h]>` con il `estimate` comando per specificare la durata della copia di prova in tempo reale. Il valore predefinito è 5m.

.Sintassi
[source, cli]
----
xcp estimate -t <n[s|m|h]> -id <name> -target <path>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.12.12:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.12.11:/temp4' to
'10.101.12.12:/temp8'...
estimate regular file copy task completed before the 1m40s duration
0 in (0/s), 0 out (0/s), 5s
0 in (0/s), 0 out (0/s), 10s
Estimated time to copy '10.101.12.11:/temp4' to '10.101.12.12:/temp8' based on a 1m40s live
test: 5.3s

Xcp command : xcp estimate -t 100 -id estimate01 -target 10.101.12.11:/temp8
Estimated Time : 5.3s
Job ID : Job_2023-04-12_08.09.16.126908_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== stima -bs <n[k]>

Utilizzare `-bs <n[k]>` con il `estimate` comando per specificare le dimensioni del blocco di lettura/scrittura. Il valore predefinito è 64k.

.Sintassi
[source, cli]
----
xcp estimate -id <name> -bs <n[k]>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id estimate01 -bs 128k

xcp: WARNING: your license will expire in less than 7 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-24_08.44.12.564441_estimate
63.2 KiB in (12.5 KiB/s), 2.38 KiB out (484/s), 5s
== Best-case estimate to copy 'xxx' given 1 gigabit of bandwidth ==
112 TiB of data at max 128 MiB/s: at least 10d13h
Xcp command : xcp estimate -id estimate01 -bs 128k
Estimated Time : 10d13h
Job ID : Job_2023-04-24_08.44.12.564441_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-24_08.44.12.564441_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== stimate -dircount <n[k]>

Utilizzare `-dircount <n[k]>` con il `estimate` comando per specificare la dimensione richiesta per la lettura delle directory. Il valore predefinito è 64k.

.Sintassi
[source, cli]
----
xcp estimate -id <name> -dircount <n[k]> -t <n> -target <path>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id csdata01 -dircount 128k -t 300 -target <path>

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 61.6 MiB free space.
Job ID: Job_2023-04-20_13.03.46.820673_estimate
Starting live test for 5m0s to estimate time to copy ‘data-set:/user1 to `<path>`...
1,909 scanned, 126 copied, 2 giants, 580 MiB in (115 MiB/s), 451 MiB out (89.5 MiB/s), 5s
1,909 scanned, 134 copied, 2 giants, 1.23 GiB in (136 MiB/s), 1015 MiB out (112 MiB/s), 10s
1,909 scanned, 143 copied, 2 giants, 1.88 GiB in (131 MiB/s), 1.54 GiB out (113 MiB/s), 15s
.
.
.
7,136 scanned, 2,140 copied, 4 linked, 8 giants, 33.6 GiB in (110 MiB/s), 32.4 GiB out (110
MiB/s), 4m57s
Sample test copy completed for, 300.03s
0 in (-7215675436.180/s), 0 out (-6951487617.036/s), 5m2s
2,186 scanned, 610 KiB in (121 KiB/s), 76.9 KiB out (15.3 KiB/s), 5m7s
Estimated time to copy ‘data-set:/user1to '10.01.12.11:/mapr11' based on a 5m0s live test:
7d6h
Xcp command : xcp estimate -id csdata01 -dircount 128k -t 300 -target 10.101.12.11:/mapr11
Estimated Time : 7d6h
Job ID : Job_2023-04-20_13.03.46.820673_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_13.03.46.820673_estimate.log
STATUS : PASSED
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 61.6 MiB free space.
[root@client1 linux]#
----
====


== stima - <n> parallela

Utilizzare `-parallel <n>` con il `estimate` comando per specificare il numero massimo di processi batch simultanei. Il valore predefinito è 7.

.Sintassi
[source, cli]
----
xcp estimate -loglevel <name> -parallel <n> -id <name>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -loglevel DEBUG -parallel 8 -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.36.45.535209_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth ==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -parallel 8 -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.36.45.535209_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.36.45.535209_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== stima -preserva-atime

Utilizzare `-preserve-atime` con il `estimate` per mantenere il tempo di accesso del file o della directory. Il valore predefinito è false.

.Sintassi
[source, cli]
----
xcp estimate -loglevel <name> -preserve-atime -id <name>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp estimate -loglevel DEBUG -preserve-atime -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.19.04.050516_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth
==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -preserve-atime -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.19.04.050516_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.19.04.050516_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== estimate -loglevel <name>

Utilizzare `-loglevel <name>` con il `estimate` Comando per impostare il livello di log; i livelli disponibili sono INFO e DEBUG. Il livello predefinito è INFO.

.Sintassi
[source, cli]
----
xcp estimate -loglevel <name> -id <name>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -loglevel DEBUG -parallel 8 -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.36.45.535209_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth ==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -parallel 8 -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.36.45.535209_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.36.45.535209_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====