---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: Installare o aggiornare file Analytics per NFS 
---
= Installare file Analytics per NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installare o aggiornare file Analytics per NFS.

Per i requisiti di sistema per NFS, consulta link:xcp-install-xcp-nfs.html["Installare XCP NFS"]. Il `configure.sh` Script installa e abilita le configurazioni predefinite DI HTTPD e PostgreSQL disponibili per il server Linux. È possibile modificare o eseguire l'aggiornamento a una versione più recente in base alle necessità e attenersi alle linee guida sulla sicurezza.

.Prima di iniziare
* Non è possibile eseguire contemporaneamente l'applicazione XCP e XCP as service sullo stesso host. Se sono in esecuzione operazioni XCP, completare le operazioni prima di avviare la configurazione.
* La macchina Linux deve essere connessa al server di repository Yum o a Internet.
* Se sulla macchina Linux è configurato un firewall, è necessario modificare le impostazioni del firewall per abilitare le porte utilizzate da XCP, il servizio XCP e i servizi utilizzati da XCP file Analytics. Per ulteriori informazioni, visitare il sito Web all'indirizzo xref:xcp-ports-used.html[Porte utilizzate da XCP].


.Fasi
. Accedere alla cartella XCP ed eseguire `./configure.sh` script. Lo script impiega da tre a dieci minuti per configurare la macchina Linux e completare le seguenti attività:
+
.. Scarica i pacchetti PostgreSQL
.. Installare il server PostgreSQL
.. Installare HTTPD
.. Utilizzare il protocollo SSL aperto per creare un certificato autofirmato (`server.key and server.crt`)
.. Creare il database XCP file Analytics


. Selezionare `option 1 Configure client system` Dal menu di configurazione XCP.
. Per una nuova installazione, aggiornare la password per l'amministratore e gli utenti del database. Per un aggiornamento, viene richiesto di interrompere il servizio XCP. Al termine, selezionare `option 0`.
. Avviare il servizio XCP. Utilizzare il seguente comando per verificare se il servizio XCP è in esecuzione: Stato del servizio xcp
. Avviare analisi file nel browser: */<ip address of linux>/xcp*.

