---
sidebar: sidebar 
permalink: xcp-nfs-reference-chmod.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Riferimento comando NFS XCP 
---
= chmod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il NFS di XCP `chmod` il comando scansiona e modifica l'autorizzazione di tutti i file per la struttura di directory specificata. Il comando 'chmod' richiede la modalità o il riferimento, la condivisione NFS o il percorso POSIX come variabile. XCP `chmod` comando modifica ricorsivamente le autorizzazioni per un determinato percorso. L'output del comando visualizza il totale dei file sottoposti a scansione e le autorizzazioni modificate nell'output.

.Sintassi
[source, cli]
----
xcp chmod -mode <value> <source NFS export path>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -mode <IP address>:/source_vol

Xcp command : xcp chmod -mode <IP address>://source_vol
Stats : 6 scanned, 4 changed mode
Speed : 1.96 KiB in (2.13 KiB/s), 812 out (882/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux] #
----
====
La seguente tabella elenca `chmod` parametri e loro descrizione.

[cols="2*"]
|===
| Parametro | Descrizione 


| <<nfs_chmod_exclude,chmod -exclude   >> | Esclude i file e le directory corrispondenti al filtro. 


| <<nfs_chmod_match,chmod -match   >> | Elabora solo i file e le directory corrispondenti al filtro. 


| <<nfs_chmod_reference,chmod -reference  >> | Specifica il file referenziato o il punto di directory. 


| <<nfs_chmod_v,chmod -v >> | Riporta l'output per ogni oggetto elaborato. 
|===


== chmod -exclude <filter>

Utilizzare `-exclude <filter>` con il `chmod` comando per escludere i file e le directory che corrispondono al filtro.

.Sintassi
[source, cli]
----
xcp chmod -exclude <filter> -mode <value> <source NFS export path>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -exclude "fnm('3.img')" -mode 770 101.11.10.10:/s_v1/D3/

Excluded: 1 excluded, 0 did not match exclude criteria
Xcp command : xcp chmod -exclude fnm('3.img') -mode 770 101.11.10.10:/s_v1/D3/
Stats : 5 scanned, 1 excluded, 5 changed mode
Speed : 2.10 KiB in (7.55 KiB/s), 976 out (3.43 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chmod -match <filter>

Utilizzare `-match <filter>` con il `chmod` comando per elaborare solo i file e le directory che corrispondono al filtro.

.Sintassi
[source, cli]
----
xcp chmod -match <filter>  -mode <value> <source NFS export path>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -match "fnm('2.img')" -mode 777 101.11.10.10:/s_v1/D2/

Filtered: 1 matched, 5 did not match
Xcp command : xcp chmod -match fnm('2.img') -mode 101.11.10.10:/s_v1/D2/
Stats : 6 scanned, 1 matched, 2 changed mode
Speed : 1.67 KiB in (1.99 KiB/s), 484 out (578/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]
----
====


== chmod -reference <reference>

Utilizzare `-reference <reference>` con il `chmod` comando per specificare il file referenziato o il punto di directory.

.Sintassi
[source, cli]
----
xcp chmod -reference <reference> <source NFS export path>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -reference 101.11.10.10:/s_v1/D1/1.txt 102.21.10.10:/s_v1/D2/

Xcp command : xcp chmod -reference 101.11.10.10:/s_v1/D1/1.txt 102.21.10.10:/s_v1/D2/
Stats : 6 scanned, 6 changed mode
Speed : 3.11 KiB in (3.15 KiB/s), 1.98 KiB out (2.00 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chmod -v

Utilizzare `-v` con il `chmod` comando per riportare l'output per ogni oggetto elaborato.

.Sintassi
[source, cli]
----
chmod -mode <value> -v <source NFS export path>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -mode 111 -v file:///mnt/s_v1/D1/

mode of 'file:///mnt/s_v1/D1' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/1.txt' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/softlink_1.img' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/softlink_to_hardlink_1.img' changed from 0777 to 0111 mode
of 'file:///mnt/s_v1/D1/1.img' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/hardlink_1.img' changed from 0777 to 0111 mode of
'file:///mnt/s_v1/D1/1.img1' changed from 0777 to 0111
Xcp command : xcp chmod -mode 111 -v file:///mnt/s_v1/D1/ Stats : 7 scanned, 7
changed mode
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====