---
sidebar: sidebar 
permalink: xcp-smb-reference-copy.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: 'Riferimento comando "copia" SMB XCP' 
---
= copia
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il `copy` Command esegue la scansione e copia dell'intera struttura della directory di origine in una condivisione SMB di destinazione. Il `copy` il comando richiede i percorsi di origine e di destinazione come variabili. I file sottoposti a scansione e copiati, il throughput/la velocità e i dettagli relativi al tempo trascorso vengono stampati sulla console ogni cinque secondi.

[NOTE]
====
* Il file di registro del runtime viene memorizzato in "C:\NetApp\XCP".
* Questo `copy` Il comando copia i dati senza un elenco di controllo di accesso (ACL).


====
.Sintassi
[source, cli]
----
xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====
La seguente tabella elenca `copy` parametri e loro descrizione.

[cols="2*"]
|===
| Parametro | Descrizione 


| <<smb_copy_help,copy -h, --help>> | Consente di visualizzare informazioni dettagliate sul `copy` comando. 


| <<copia -v>> | Aumentare la verbosità del debug. 


| <<smb_copy_parallel,copia -parallela  >> | Specifica il numero di processi simultanei (impostazione predefinita: <cpu-count>). 


| <<smb_copy_match,copia -corrisponde a  >> | Elabora solo i file e le directory corrispondenti al filtro (vedere `xcp help - match` per ulteriori informazioni). 


| <<smb_copy_exclude,copia -exclude  >> | Esclude solo i file e le directory nel filtro 


| <<copia -preserva-atime>> | Ripristina l'ultima data di accesso sull'origine. 


| <<smb_copy_acl,copy - acl (copia - acl)>> | Copia le informazioni di sicurezza. 


| <<smb_copy_acl,copy -fallback-user  >> | Specifica l'utente Active Directory o l'utente locale (non di dominio) sul computer di destinazione che riceve le autorizzazioni degli utenti locali (non di dominio) del computer di origine. Ad esempio, dominio\amministratore. 


| <<smb_copy_acl,copia -fallback-group  >> | Specifica il gruppo Active Directory o il gruppo locale (non di dominio) sul computer di destinazione che riceve le autorizzazioni dei gruppi di computer di origine locali (non di dominio). Ad esempio, dominio\amministratori. 


| <<smb_copy_root,copy -root>> | Copia gli ACL per una directory principale. 


| <<smb_copy_aclverify,copia -aclverify {yes,no}>> | Fornisce un'opzione per ignorare o includere la verifica ACL durante l'operazione di copia -ACL. 


| <<copy -noownership>> | Non copia la proprietà. 


| <<smb_copy_bs,copia -bs  >> | Dimensione blocco lettura/scrittura (default:1M) 


| <<copy -ads>> | Copia i flussi di dati NTFS alternativi dalla condivisione SMB di origine alla condivisione SMB di destinazione. 
|===


== copy -h, --help

Utilizzare `-h` e. `–-help` parametri con `copy` per visualizzare informazioni dettagliate sul `copy` comando

.Sintassi
[source, cli]
----
xcp copy –help
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp copy –help

usage: xcp copy [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve- atime] [-acl] [-fallback-user FALLBACK_USER]
[-fallback-group FALLBACK_GROUP] [-loglevel <name>] [-root] [-noownership] [- aclverify {yes,no}] [-bs <n>] [-ads]
         source target

positional arguments:
   source
   target

optional arguments:
-h, --help            show this help message and exit
-v                    increase debug verbosity
-parallel <n>         number of concurrent processes (default: <cpu-count>)
-match <filter>       only process files and directories that match the filter (see `xcp help -match` for details)
-exclude <filter>     Exclude files and directories that match the filter (see `xcp help - exclude` for details)
-preserve-atime       restore last accessed date on source
-acl                  copy security information
-fallback-user FALLBACK_USER
                      the name of the user on the target machine to receive the permissions of local (non-domain) source machine users (eg. domain\administrator)
-fallback-group FALLBACK_GROUP
                      the name of the group on the target machine to receive the permissions of local (non-domain) source machine groups (eg. domain\administrators)
-loglevel <name>      option to set log level filter (default:INFO)
-root                 copy acl for root directory
-noownership          do not copy ownership
-aclverify {yes,no}   choose whether you need to skip acl verification
-bs <n>               read/write block size for copy (default: 1M)
-ads                  copy NTFS alternate data streams.
----
====


== copia -v

Utilizzare `-v` con il `copy` comando per fornire informazioni dettagliate sul debug.

.Sintassi
[source, cli]
----
xcp copy -v \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1

failed to set attributes for "d1": (5, 'CreateDirectory', 'Access is denied.')
failed to copy "f1.txt": (5, 'CreateFile', 'Access is denied.')
failed to set attributes for "": (5, 'SetFileAttributesW', 'Access is denied.') error setting timestamps on "": errno (code: 5) Access is denied.
H:\p 4\xcp_latest\xcp_cifs\xcp\ main .py copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1
3 scanned, 0 matched, 0 skipped, 1 copied, 0 (0/s), 3 errors
Total Time : 3s
STATUS : FAILED
----
====


== copia - <n> parallela

Utilizzare `-parallel <n>` con il `copy` Comando per impostare un numero maggiore o minore di processi simultanei XCP. Il valore predefinito per `-parallel` È uguale al conteggio CPU.


NOTE: Il valore massimo per n è 61.

.Sintassi
[source, cli]
----
xcp copy -parallel <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -parallel 7	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -parallel 7 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0errors
Total Time : 2s
STATUS : PASSED
----
====


== copia - corrisponde a <filter>

Utilizzare `-match <filter>` con il `copy` comando per copiare solo i dati che corrispondono all'argomento passato.

.Sintassi
[source, cli]
----
xcp copy -match <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -match 'gx' in name \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 5 matched, 4 copied, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


== copia -exclude <filter>

Utilizzare `-exclude <filter>` con il `copy` comando per copiare solo i dati esclusi.

.Sintassi
[source, cli]
----
xcp copy -exclude <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
Nell'esempio seguente, i file e le directory che hanno la stringa "risincronizza" nel loro nome sono stati esclusi per la copia.

.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -exclude "'resync' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address or hostname of SMB server>\dest_share


xcp copy -exclude 'resync' in name \\<IP address or hostname of SMB server>\source_share \\\\<IP address or hostname of SMB server>\dest_share
18 scanned, 2 excluded, 0 skipped, 15 copied, 122KiB (50.5KiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copia -preserva-atime

Utilizzare `-preserve-atime` con il `copy` Comando per ripristinare "atime" al valore originale prima che XCP legga il file.

.Sintassi
[source, cli]
----
xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copy -acl -fallback-user <fallback_user> -fallback-group <fallback_group>

Utilizzare `-acl` con il `copy` Comando per attivare il trasferimento dei descrittori di protezione (ACL).

Utilizzare `-acl` con il `-fallback-user` e. `-fallback-group` Opzioni per specificare un utente e un gruppo sul computer di destinazione o da Active Directory per ricevere le autorizzazioni di utenti o gruppi locali (non di dominio) del computer di origine. Ciò non fa riferimento agli utenti senza pari di Active Directory.

.Sintassi
[source, cli]
----
xcp copy -acl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----


== copia -aclverify {yes,no}

Utilizzare `-aclverify {yes,no}` con il `copy` Comando che fornisce un'opzione per saltare o includere la verifica ACL durante un'operazione di copia ACL.

È necessario utilizzare `-aclverify {yes,no}` con il `copy -acl` comando. Per impostazione predefinita, l'operazione di copia ACL verifica gli ACL. Se si imposta `-aclverify` opzione a. `no`, È possibile ignorare la verifica ACL e la `fallback-user` e. `fallback-group` le opzioni non sono obbligatorie. Se si imposta `-aclverify` a. `yes`, richiede l' `fallback-user` e. `fallback-group` opzioni, come illustrato nell'esempio seguente.

.Sintassi
[source, cli]
----
xcp copy -acl -aclverify yes -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\NetApp\xcp>xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group"
\\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 15s, 0 acls copied xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (634/s), 0 errors, 11 acls copied
Total Time : 16s
STATUS : PASSED

C:\NetApp\xcp>xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (5.61KiB/s), 0 errors, 11 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== copy -root

Utilizzare `-root` con il `copy` Comando per copiare gli ACL per la directory principale.

.Sintassi
[source, cli]
----
xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 200 (108/s), 0 errors, 6 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== copy -noownership

Utilizzare `-noownership` con il `copy` comando per specificare di non copiare la proprietà dall'origine alla destinazione. È necessario utilizzare `-noownership` con `-acl` opzione e richiede `fallback-user` e. `fallback-group` come parametri obbligatori.

.Sintassi
[source, cli]
----
xcp.exe copy -acl -noownership -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 135 copied, 4.26MiB (872KiB/s), 0 errors, 15s, 137 acls copied xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (1.01MiB/s), 0 errors, 567 acls copied
Total Time : 17s
STATUS : PASSED
----
====


== copy -bs <n>

Utilizzare `-bs <n>` con il `copy` comando per fornire dimensioni dei blocchi di lettura/scrittura. Il valore predefinito è 1M.

.Sintassi
[source, cli]
----
xcp.exe copy -bs <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\Netapp\xcp>xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (6.75MiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copy -ads

Utilizzare `-ads` con il `copy` Comando per copiare flussi di dati NTFS alternativi dalla condivisione SMB di origine alla condivisione SMB di destinazione.

.Sintassi
[source, cli]
----
xcp copy -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

6   scanned, 0 matched, 0 skipped, 3 copied, 13 (2.41/s), 0 errors, 5s, 10 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	10s, 11 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	15s, 12 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	20s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	25s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	30s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	35s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	40s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	45s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	2m15s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	3m5s, 13 ads copied
xcp copy -ads \\<source_IP_address>\source_share\src \\<desination_IP_address>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 26 (0.137/s), 0 errors, 14 ads copied
Total Time : 3m9s
STATUS : PASSED
----
====