---
sidebar: sidebar 
permalink: xcp-run-multiple-jobs-on-same-host.html 
keywords: xcp, configure, nfs, posix, connector 
summary: Il connettore POSIX offre a XCP la possibilità di accedere a qualsiasi file system montato su Linux, come NFSv4, XFS e Veritas. 
---
= Eseguire più lavori XCP sullo stesso host XCP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da XCP 1,9.2, è possibile eseguire più lavori o comandi XCP su un singolo host XCP, a condizione che l'host disponga di risorse sufficienti per ciascun lavoro. Quando si esegue un comando che supporta più processi, XCP utilizza una memoria host minima per completare il processo, creando così la capacità di eseguire processi aggiuntivi sulla stessa configurazione host.



== Requisiti minimi di sistema

Per ogni lavoro XCP, è necessario consentire fino a 64 GB di memoria host e otto core per migrazioni da medie a grandi dimensioni.


NOTE: L'esecuzione di più processi XCP sullo stesso host non è supportata per la migrazione dei dati SMB.



== Registrazione

Per impostazione predefinita, ogni lavoro XCP viene registrato in un file di log separato, univoco per l'ID lavoro. Questo meccanismo di logging funziona bene quando si eseguono più lavori sullo stesso host singolo. NetApp sconsiglia di modificare `xcpLogConfig.Json` file per utilizzare un singolo `xcp.log` File per registrare più lavori XCP eseguiti in parallelo sullo stesso host.



== Comandi supportati

L'esecuzione di più processi XCP sullo stesso host è supportata con i seguenti comandi XCP:

* `scan`
* `copy`
* `resume`
* `verify`
* `isync`
* `chmod`
* `chown`
* `delete`




== Comandi non supportati

L'esecuzione di più processi XCP sullo stesso host non è supportata con `sync` comando.
