---
sidebar: sidebar 
permalink: xcp-environment-variable.html 
keywords: netapp, xcp, configure, configuring, how, performing, tuning, nfs, enviroment, 
summary: 'Variabile di ambiente (solo NFS)' 
---
= Variabile di ambiente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configurazione opzionale delle variabili di ambiente per i sistemi NFS XCP.


NOTE: Un utente non root può anche utilizzare le seguenti variabili.

La variabile di ambiente `XCP_CONFIG_DIR` sovrascrive la posizione predefinita, `/opt/NetApp/xFiles/xcp`. Se impostato, il valore dovrebbe essere un percorso del file system del sistema operativo, possibilmente verso una directory NFS montata. Quando il `XCP_CONFIG_DIR` viene impostata una variabile, viene creata una nuova directory con lo stesso nome del nome host all'interno del percorso della directory di configurazione personalizzata, i nuovi log vengono memorizzati in questa posizione.

[listing]
----
[root@localhost /]# export XCP_CONFIG_DIR ='/tmp/xcp_config_dir_path'
----
La variabile di ambiente `XCP_LOG_DIR` Sovrascrive la posizione predefinita in cui è memorizzato il registro XCP nella directory di configurazione. Se impostato, il valore dovrebbe essere un percorso del file system del sistema operativo, possibilmente verso una directory NFS montata. Quando il  `XCP_LOG_DIR` viene impostata una variabile, viene creata una nuova directory con lo stesso nome del nome host all'interno del percorso personalizzato della directory di log, i nuovi log vengono memorizzati in questa posizione.

[listing]
----
[root@localhost /]# export XCP_LOG_DIR='/tmp/xcp_log_dir_path'
----
La variabile di ambiente `XCP_CATALOG_PATH` sovrascrive l'impostazione in xcp.ini. Se impostato, il valore deve essere nel formato del percorso xcp, `server:export[:subdirectory]`.

[listing]
----
[root@localhost /]# export XCP_CATALOG_PATH='10.61.82.210:/vol/xcpvol/'
----

NOTE: Per un utente non root, è necessario sostituire `XCP_CATALOG_PATH` Dal percorso esportato con il percorso POSIX.
