---
sidebar: sidebar 
permalink: xcp-smb-reference-sync.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: 'Riferimento comando "Sync" SMB XCP' 
---
= sincronizzazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il `sync` il comando analizza le modifiche e le modifiche nelle condivisioni di origine e destinazione in parallelo e applica le azioni appropriate alla destinazione per assicurarsi che la destinazione sia identica all'origine. Il `sync` il comando confronta il contenuto dei dati, i timestamp, gli attributi dei file, la proprietà e le informazioni sulla sicurezza.

.Sintassi
[source, cli]
----
xcp sync \\<source SMB share> \\<IP address of SMB destination server>
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====
La seguente tabella elenca `sync` parametri e loro descrizione.

[cols="2*"]
|===
| Parametro | Descrizione 


| <<smb_sync_help,sync -h, --help>> | Mostra questo messaggio di aiuto e esci. 


| <<sincronizza -v>> | Aumentare la verbosità del debug. 


| <<smb_sync_parallel,sincronizza -parallelo  >> | Numero di processi simultanei (impostazione predefinita: <cpu-count>). 


| <<smb_sync_match,sync -match  >> | Elaborare solo file e directory corrispondenti al filtro (vedere `xcp help - match` per ulteriori informazioni). 


| <<smb_sync_exclude,sync -exclude  >> | Escludere solo i file e le directory nel filtro. 


| <<sync -preserve-atime>> | Ripristina l'ultima data di accesso sull'origine. 


| <<sync -noatime>> | Non controllare il tempo di accesso ai file. 


| <<sync -noctime>> | Non controllare l'ora di creazione del file. 


| <<sync -nomtime>> | Non controllare l'ora di modifica del file. (Questa opzione è obsoleta. La sincronizzazione continuerà ad essere eseguita senza questa opzione.) 


| <<sync -noattrs>> | Non controllare gli attributi. 


| <<sync -noownership>> | Non verificare la proprietà. 


| <<sync_smb_atime,sync -atimewindow  >> | Differenza di tempo di accesso accettabile, in secondi. 


| <<sync_smb_ctime,sync -ctimewindow  >> | Differenza di tempo di creazione accettabile, in secondi. 


| <<sync_smb_mtime,sync -mtimewindow  >> | Differenza di tempo di modifica accettabile, in secondi, 


| <<sync_smb_acl,sync -acl>> | Copiare le informazioni di protezione. 


| <<sync_smb_acl,sync -fallback-user  >> | Utente Active Directory o utente locale (non di dominio) sul computer di destinazione per ricevere le autorizzazioni degli utenti locali (non di dominio) del computer di origine (ad esempio: Dominio\amministratore). 


| <<sync_smb_acl,sync -fallback-group  >> | Gruppo Active Directory o gruppo locale (non di dominio) sul computer di destinazione per ricevere le autorizzazioni dei gruppi di computer di origine locali (non di dominio) (ad esempio: Dominio\amministratori). 


| <<sync -l>> | Aumenta i dettagli di output. 


| <<smb_sync_root,sync -root>> | Sincronizza ACL per la directory principale. 


| <<smb_sync_onlyacl,sync -onliac>> | Copiare solo le informazioni di protezione. 


| <<smb_sync_aclverify,sync -aclverify{yes,no} >> | Fornire un'opzione per includere o ignorare la verifica ACL durante l'operazione di sincronizzazione ACL. 


| <<smb_sync_bs,sync -bs  >> | Dimensione blocco lettura/scrittura (default:1M). 


| <<sync -ads>> | Utilizzare `sync` con il `-ads` Flag per cercare modifiche e modifiche di flussi di dati alternativi nella condivisione SMB di origine e di destinazione. In caso di modifiche, applica la modifica al target a.
assicurarsi che la destinazione sia identica alla sorgente. 
|===


== sync -h, --help

Utilizzare `-h` e. `–-help` parametri con `sync` per visualizzare informazioni dettagliate sul `sync` comando

.Sintassi
[source, cli]
----
xcp sync -–help
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp sync --help
usage: xcp sync [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve-atime] [-noatime] [-noctime] [-nomtime] [-noattrs] [-atimewindow <float>]
[-ctimewindow <float>] [-mtimewindow <float>] [-acl] [-fallback-user FALLBACK_USER] [-fallback-group FALLBACK_GROUP] [-loglevel <name>] [-l] [-root]
[-noownership] [-onlyacl] [-aclverify {yes,no}] [-bs <n>] [-ads] source target

Note: ONTAP does not let a SMB client modify COMPRESSED or ENCRYPTED attributes. XCP sync will ignore these file attributes.

positional arguments:
   source
   target

optional arguments:
   -h, --help              show this help message and exit
   -v                      increase debug verbosity
   -parallel <n>           number of concurrent processes (default: <cpu-count>)
   -match <filter>         only process files and directories that match the filter (see `xcp help -match` for details)
   -exclude <filter>       Exclude files and directories that match the filter (see `xcp help -exclude` for details)
   -preserve-atime	       restore last accessed date on source
   -noatime                do not check file access time
   -noctime                do not check file creation time
   -nomtime                do not check file modification time
   -noattrs                do not check attributes
   -atimewindow <float>    acceptable access time difference in seconds
   -ctimewindow <float>    acceptable creation time difference in seconds
   -mtimewindow <float>    acceptable modification time difference in seconds
   -acl                    copy security information
   -fallback-user FALLBACK_USER
                           the name of the user on the target machine to receive the permissions of local (non-domain) source machine users (eg. domain\administrator)
   -fallback-group FALLBACK_GROUP
                           the name of the group on the target machine to receive the permissions of local (non-domain) source machine groups (eg. domain\administrators)
   -loglevel <name>        option to set log levelfilter
   -l                      increase output detail
   -root                   sync acl for root directory
   -noownership            do not sync ownership
   -onlyacl                sync only acls
   -aclverify {yes,no}     choose whether you need to skip acl verification
   -bs <n>                 read/write block size for sync (default: 1M)
   -ads                    sync ntfs alternate data stream
----
====


== sincronizza -v

Utilizzare `-v` con il `sync` comando per fornire informazioni dettagliate sul debug.

.Sintassi
[source, cli]
----
xcp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\XCP>xcp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
ERROR failed to remove from target "assembly\GAC_32\Microsoft.CertificateServices.PKIClient.Cmdlets\v4.0_6.3.0.0 31bf3856ad364e35\p ki.psd1": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_tar shil\\assembly\\GAC_32\\Microsoft.CertificateServices.PKIClient.Cmdlets\\v4.0_6.3.0.0 31bf3856ad 364e35\\pki.psd1'
ERROR failed to remove from target "assembly\GAC_64\Microsoft.GroupPolicy.AdmTmplEditor\v4.0_6.3.0.0 31bf3856ad364e35\Microsoft.Gro upPolicy.AdmTmplEditor.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\10.61.
\vol_SMB_target_xxxxxx\\assembly\\GAC_64\\Microsoft.GroupPolicy.AdmTmplEditor\\v4.0_6.3.0.0 31bf 3856ad364e35\\Microsoft.GroupPolicy.AdmTmplEditor.dll'
1,933 scanned, 1,361 compared, 2 errors, 0 skipped, 0 copied, 1,120 removed, 5s ERROR failed to remove from target
"assembly\GAC_64\System.Printing\v4.0_4.0.0.0 31bf3856ad364e35\System.Printing.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\
4\\System.Printing\\v4.0_4.0.0.0 31bf3856ad364e35\\System.Printing.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\Microsoft.PowerShell.Workflow.ServiceCore\v4.0_3.0.0.0 31bf3856ad364e35\Micro soft.PowerShell.Workflow.ServiceCore.dll": [Errno 13] Access is denied: '\\\\
\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.PowerShell.Workflow.ServiceCore\\v4
.0_3.0.0.0  31bf3856ad364e35\\Microsoft.PowerShell.Workflow.ServiceCore.dll' ERROR failed to remove from target "assembly\GAC_MSIL\Microsoft.RightsManagementServices.ServerManager.DeploymentPlugin\v4.0_6.3.0.0
31bf3856ad364e35\Microsoft.RightsManagementServices.ServerManager.Deploymen n.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination
server>\\vol_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.RightsManagementServices.ServerMana ger.DeploymentPlugin\\v4.0_6.3.0.0 31bf3856ad364e35\\Mic
.RightsManagementServices.ServerManager.DeploymentPlugin.dll'
ERROR failed to remove from target
"assembly\GAC_MSIL\Microsoft.WSMan.Management\v4.0_3.0.0.0 31bf3856ad364e35\Microsoft.WSMan.Mana gement.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_
_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.WSMan.Management\\v4.0_3.0.0.0 31bf3856ad364e35\\Microsof t.WSMan.Management.dll'
ERROR failed to remove from target
"assembly\GAC_MSIL\PresentationUI\v4.0_4.0.0.0 31bf3856ad364e35\PresentationUI.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\
SIL\\PresentationUI\\v4.0_4.0.0.0 31bf3856ad364e35\\PresentationUI.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\System.IO.Compression.FileSystem\v4.0_4.0.0.0 b77a5c561934e089\System.IO.Comp ression.FileSystem.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\10.61.71.5
_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\System.IO.Compression.FileSystem\\v4.0_4.0.0.0 b77a5c561 934e089\\System.IO.Compression.FileSystem.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\System.IdentityModel.Selectors\v4.0_4.0.0.0 b77a5c561934e089\System.IdentityM odel.Selectors.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\v s_target_xxxxxx\\assembly\\GAC_MSIL\\System.IdentityModel.Selectors\\v4.0_4.0.0.0 b77a5c561934e0 89\\System.IdentityModel.Selectors.dll'
2,747 scanned, 2,675 compared, 9 errors, 0 skipped, 0 copied, 2,624 removed, 10s ERROR failed to remove from target
"assembly\GAC_MSIL\System.Web.DataVisualization\v4.0_4.0.0.0 31bf3856ad364e35\System.Web.DataVis ualization.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_c
rget_xxxxxx\\assembly\\GAC_MSIL\\System.Web.DataVisualization\\v4.0_4.0.0.0 31bf3856ad364e35\\Sy stem.Web.DataVisualization.dll'
cp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
2,831 scanned, 0 copied, 2,831 compared, 0 removed, 10 errors Total Time : 10s
STATUS : PASSED
----
====


== sync -parallel <n>

Utilizzare `-parallel <n>` con il `sync` Comando per impostare un numero maggiore o minore di processi simultanei XCP. Il `sync -parallel <n>` il comando si sincronizza con il numero di processi simultanei (impostazione predefinita: <cpu-count>).


NOTE: Il valore massimo per n è 61.

.Sintassi
[source, cli]
----
xcp sync -parallel <n>> \\<IP address or hostname of SMB server>\volxcp\\<IP address of SMB destination server>\xcp1_test1
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\xcp>xcp sync -parallel 5 \\<IP address or hostname of SMB server>\volxcp\\<IP address of SMB destination server>\xcp1_test1
658 scanned, 244 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 5s
658 scanned, 606 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 10s
658 scanned, 658 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 10s
Sending statistics...
----
====


== sincronizza - corrisponde a <filter>

Utilizzare `-match <filter>` con il `sync` comando per eseguire la scansione della struttura di origine e di destinazione e confrontare solo i file o le directory che corrispondono all'argomento del filtro. In caso di differenze, il comando applica le azioni necessarie sulla destinazione per mantenerle sincronizzate.

.Sintassi
[source, cli]
----
xcp sync -match <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -match 'gx' in name \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 10 compared, 0 removed, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== sync -exclude <filter>

Utilizzare `-exclude <filter>` con il `sync` comando per escludere solo file e directory nel filtro.

.Sintassi
[source, cli]
----
xcp sync -exclude <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp sync -exclude "path('*Exceptions*')" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -exclude path('*Exceptions*') \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
451 scanned, 427 excluded, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== sync -preserve-atime

Utilizzare `-preserve-atime` con il `sync` Comando per ripristinare "atime" al valore originale prima che XCP legga il file.

.Sintassi
[source, cli]
----
xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 4s
STATUS : PASSED
----
====


== sync -noatime

Utilizzare `-noatime` con il `sync` comando per sincronizzare tutte le differenze tra l'origine e la destinazione, escludendo i file che hanno solo differenze nei tempi di accesso.

.Sintassi
[source, cli]
----
xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED

----
====


== sync -noctime

Utilizzare `-noctime` con il `sync` comando per sincronizzare tutte le differenze tra l'origine e la destinazione, escludendo i file che presentano solo differenze nel tempo di creazione.

.Sintassi
[source, cli]
----
xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -nomtime

Utilizzare `-nomtime` con il `sync` comando per sincronizzare tutte le differenze tra l'origine e la destinazione, esclusi i file che hanno solo differenze nel tempo di modifica. (Questa opzione è obsoleta. Il `sync` il comando continuerà ad essere eseguito senza questa opzione).

.Sintassi
[source, cli]
----
xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -noattrs

Utilizzare `-noattrs` con il `sync` comando per sincronizzare tutte le differenze tra l'origine e la destinazione, esclusi i file che presentano solo differenze negli attributi del file. XCP copia un file solo quando ha contenuto diverso (gli ACL vengono trasferiti).

.Sintassi
[source, cli]
----
xcp sync -noattrs \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noattrs	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noattrs	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noattrs \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -noownership

Utilizzare `-noownership` con il `sync` comando per sincronizzare tutte le differenze tra l'origine e la destinazione, esclusi i file che hanno solo differenze di proprietà.

.Sintassi
[source, cli]
----
xcp sync -noownership \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
----
.Mostra esempio
[%collapsible]
====
[listing]
----
>xcp sync -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

      Truncated Output
302,909 scanned,    301,365 compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m46s
307,632	scanned,	303,530	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m51s
308,434	scanned,	305,462	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m56s
310,824	scanned,	307,328	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m1s
313,238	scanned,	310,083	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m6s
314,867	scanned,	313,407	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m11s
318,277	scanned,	315,856	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m17s
321,005	scanned,	318,384	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m22s
322,189	scanned,	321,863	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m27s
323,906	scanned,	323,906	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m29s

xcp sync -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
323,906 scanned, 0 copied, 323,906 compared, 0 removed, 0 errors
Total Time : 10m29s
STATUS : PASSED
----
====


== sync -atimewindow <float>

Utilizzare `-atimewindow <float>` con il `sync` comando per specificare la differenza accettabile, in secondi, per l'ora di un file dall'origine alla destinazione. XCP non riporta i file come diversi se la differenza di tempo è inferiore a <value>.

.Sintassi
[source, cli]
----
xcp sync -atimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
Nell'esempio seguente, XCP accetta una differenza di tempo fino a 10 minuti tra i file di origine e di destinazione e non aggiorna l'atime sulla destinazione.

.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share
xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share

xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -ctimewindow <float>

Utilizzare `-ctimewindow <float>` con il `sync` comando per specificare la differenza accettabile, in secondi, per la ctime di un file dall'origine alla destinazione. XCP non riporta i file come diversi quando la differenza in ctime è inferiore a <value>.

.Sintassi
[source, cli]
----
xcp sync -ctimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
Nell'esempio seguente, XCP accetta una differenza di tempo per un massimo di 10 minuti tra i file di origine e di destinazione e non aggiorna il tempo di coda sulla destinazione.

.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -mtimewindow <float>

Utilizzare `-mtimewindow <float>` con il `sync` comando per specificare la differenza accettabile, in secondi, per la mtime di un file dall'origine alla destinazione. XCP non riporta i file come diversi quando la differenza in mtime è inferiore a <value>.

.Sintassi
[source, cli]
----
xcp sync -mtimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors Total Time : 3s
STATUS : PASSED
----
====


== sync -acl -fallback-user <fallback_user> -fallback-group <fallback_group>

Utilizzare `-acl`, `-fallback-user` e. `-fallback-group` parametri con `sync` per confrontare i dati e le informazioni di sicurezza provenienti dall'origine con la destinazione e applicare le azioni richieste sulla destinazione. Il `-fallback-user` e. `-fallback-group` Le opzioni sono un utente o un gruppo sul computer di destinazione o in Active Directory che ricevono le autorizzazioni degli utenti o dei gruppi di origine locali (non di dominio).


NOTE: Non è possibile utilizzare `-acl` senza `-fallback-user` e. `-fallback-group` opzioni.

.Sintassi
[source, cli]
----
xcp sync -acl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\performance_SMB_home_dirs \\<IP address of SMB destination server>\performance_SMB_home_dirs
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\xcp>xcp sync -acl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
10,796	scanned,	4,002	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	s
15,796	scanned,	8,038	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,505	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,707	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,730	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,749	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,765	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,786	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,956	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	9,320	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	9,339	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	9,363	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	m0s
15,796	scanned,	10,019	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m5s
15,796	scanned,	10,042	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m10s
15,796	scanned,	10,059	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m15s
15,796	scanned,	10,075	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m20s
15,796	scanned,	10,091	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m25s
15,796	scanned,	10,108	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m30s
15,796	scanned,	10,929	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m35s
15,796	scanned,	12,443	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m40s
15,796	scanned,	13,963	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m45s
15,796	scanned,	15,488	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m50s
15,796	scanned,	15,796	compared,	0	errors,	0	skipped,     0	copied	0	removed,	1m51s

xcp sync -acl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
15,796 scanned, 0 copied, 15,796 compared, 0 removed, 0 errors
Total Time : 1m51
STATUS : PASSED
----
====


== sync -l

Utilizzare `-l` con il `sync` Comando per fornire informazioni di registrazione dettagliate nell'output standard per tutte le azioni eseguite da XCP sulla destinazione.

.Sintassi
[source, cli]
----
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

File "atime" changed, timestamps set for "agnostic"
File "atime" changed, timestamps set for "<root>"
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -root

Utilizzare `-root` con il `sync` Comando per sincronizzare gli ACL per la directory principale.

.Sintassi
[source, cli]
----
xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
12 scanned, 0 copied, 12 compared, 0 skipped, 0 removed, 0 errors, 1 acls copied
Total Time : 2s
STATUS : PASSED
----
====


== sync -onlyacl-fallback-user <fallback_user> -fallback-group <fallback_group>

Utilizzare `-onlyacl`, `-fallback-user`, e. `-fallback-group` parametri con `sync` per confrontare le informazioni di sicurezza tra l'origine e la destinazione e applicare le azioni richieste sulla destinazione. Il `-fallback-user` e. `-fallback-group` Si tratta di un utente o di un gruppo sul computer di destinazione o in Active Directory che riceve le autorizzazioni degli utenti o dei gruppi di origine locali (non di dominio).


NOTE: Non è possibile utilizzare `-onlyacl` parametro senza `-fallback-user` e. `-fallback-group` opzioni.

.Sintassi
[source, cli]
----
xcp sync -onlyacl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\Users\ctladmin\Desktop>xcp sync -onlyacl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

8,814 scanned,	0	copied,	620	compared,	0	skipped,	0	removed,	0	errors,	6s
9,294 scanned,	0	copied,	2,064	compared,	0	skipped,	0	removed,	0	errors,	11s
12,614 scanned,	0	copied,	3,729	compared,	0	skipped,	0	removed,	0	errors,	16s
13,034 scanned,	0	copied,	5,136	compared,	0	skipped,	0	removed,	0	errors,	21s
14,282 scanned,	0	copied,	7,241	compared,	0	skipped,	0	removed,	0	errors,	26s
14,282 scanned,	0	copied,	8,101	compared,	0	skipped,	0	removed,	0	errors,	31s
14,282 scanned,	0	copied,	8,801	compared,	0	skipped,	0	removed,	0	errors,	36s
14,282 scanned,	0	copied,	9,681	compared,	0	skipped,	0	removed,	0	errors,	41s
14,282 scanned,	0	copied,	10,405	compared,	0	skipped,	0	removed,	0	errors,	46s
14,282 scanned,	0	copied,	11,431	compared,	0	skipped,	0	removed,	0	errors,	51s
14,282 scanned,	0	copied,	12,471	compared,	0	skipped,	0	removed,	0	errors,	56s
14,282 scanned,	0	copied,	13,495	compared,	0	skipped,	0	removed,	0	errors,	1m1s
14,282 scanned,	0	copied,	14,282	compared,	0	skipped,	0	removed,	0	errors,	1m6s

xcp sync -onlyacl -preserve-atime -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
14,282 scanned, 0 copied, 14,282 compared, 0 skipped, 0 removed, 0 errors
Total Time : 1m7s
STATUS : PASSED

----
====


== sync -aclverify{yes,no}

Utilizzare `-aclverify{yes,no}` con il `sync` Comando per fornire un'opzione per includere o ignorare la verifica ACL durante l'operazione di sincronizzazione ACL. Questa opzione può essere utilizzata solo con `sync -acl` e. `sync -onlyacl` comandi. La sincronizzazione ACL esegue la verifica ACL per impostazione predefinita. Se si imposta `-aclverify` opzione a. `no`, È possibile ignorare la verifica ACL e la `fallback-user` e. `fallback-group` le opzioni non sono obbligatorie. Se si imposta `-aclverify` a. `yes`, richiede l' `fallback-user` e. `fallback-group` opzioni, come illustrato nell'esempio seguente.

.Sintassi
[source, cli]
----
xcp sync -acl -aclverify yes -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\NetApp\xcp>xcp sync -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 5s, 0 acls copied
25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 10s, 0 acls copied
25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 15s, 0 acls copied xcp sync -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
25 scanned, 1 copied, 25 compared, 0 skipped, 0 removed, 0 errors, 12 acls copied Total Time : 16s
STATUS : PASSED
C:\NetApp\xcp>xcp sync -acl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -acl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
27 scanned, 1 copied, 27 compared, 0 skipped, 0 removed, 0 errors, 13 acls copied Total Time : 2s
STATUS : PASSED
C:\NetApp\xcp>xcp sync -onlyacl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 5s, 0 acls copied
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 10s, 0 acls copied
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 15s, 0 acls copied xcp sync -onlyacl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
C:\NetApp\xcp>xcp sync -onlyacl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -onlyacl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 11 acls copied
Total Time : 2s
STATUS : PASSED
----
====


== sync -bs <n>

Utilizzare `-bs <n>` con il `sync` comando per fornire dimensioni dei blocchi di lettura/scrittura. Il formato predefinito è 1M.

.Sintassi
[source, cli]
----
xcp.exe sync -bs <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp.exe sync -bs 64k \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
1,136 scanned, 0 copied, 1,135 compared, 0 skipped, 95 removed, 0 errors, 5s
xcp.exe sync -bs 64k \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share 1,136 scanned, 283 copied, 1,136 compared, 0 skipped, 283 removed, 0 errors
Total Time : 10s
STATUS : PASSED
----
====


== sync -ads

Utilizzare `-ads` con il `sync` Comando per cercare modifiche e modifiche a flussi di dati alternativi nella condivisione SMB di origine e di destinazione. In caso di modifiche, applica la modifica alla destinazione per assicurarsi che la destinazione sia identica all'origine.

.Sintassi
[source, cli]
----
xcp sync -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Mostra esempio
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp sync -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	10s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	15s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	20s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	25s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	30s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	1m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	2m50s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	2m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	3m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	3m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	4m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	4m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m5s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m10s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	6m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	6m5s, 1 ads copied
xcp sync -ads \\<source_IP_address>\source_share\src \\<dest_IP_addess>\dest_share
13 scanned, 1 copied, 13 compared, 0 skipped, 0 removed, 0 errors, 1 ads copied
Total Time : 6m9s
STATUS : PASSED
----
====