---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-smb.html 
keywords: netapp, xcp, install, installing, file, analytics, smb, upgrade, upgrading 
summary: Installare o aggiornare file Analytics per SMB 
---
= Installare file Analytics per SMB
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installare o aggiornare file Analytics per SMB.

.A proposito di questa attività
Per i requisiti di sistema per SMB, vedere link:xcp-install-xcp-smb.html["Installare XCP SMB"].

.Prima di iniziare
* Per utilizzare il servizio SMB XCP, è necessario configurare XCP file Analytics per NFS su una macchina Linux.
* Assicurarsi che il servizio XCP sia in esecuzione sulla macchina Linux, prima di iniziare la configurazione di XCP file Analytics su una macchina Windows.




== Nuova installazione di file Analytics per SMB

Per eseguire una nuova installazione di file Analytics per SMB, attenersi alla seguente procedura.

.Fasi
. Copiare il `xcp.exe` Sul tuo Windows `C:` disco, questo binario è disponibile all'interno `/xcp/windows` dopo aver sciolto il `tgz` file.
. Scaricare il file di licenza XCP da link:https://xcp.netapp.com/["Sito XCP"^].
. Creare la cartella `C:\\NetApp\XCP` E copiare la licenza XCP in questa posizione.
. Attivare la licenza XCP utilizzando il seguente comando al prompt dei comandi:  `xcp.exe activate`
. Nel prompt dei comandi dell'interfaccia utente di Windows, eseguire `xcp configure`.
. Quando richiesto, fornire l'indirizzo IP della macchina Linux in cui è configurato il server XCP file Analytics.
. Copiare il `server.key` e. `server.crt` file da `/opt/NetApp/xFiles/xcp/` (Nella casella Linux in cui XCP file Analytics è già configurato) su `C:\NetApp\XCP`.
+
In alternativa, se si dispone di un certificato CA, inserire il certificato in `C:\NetApp\XCP` con lo stesso nome e gli stessi interni.

. Andare sul computer Windows ed eseguire `xcp listen`, Ora XCP file Analytics per SMB è configurato. Tenere il finestrino aperto per eseguire continuamente il servizio.
. Avviare file Analytics su un browser supportato: `\https://<ip address of linux>/xcp`
+
Fare riferimento a. link:xcp-install-xcp-smb.html["Installare XCP SMB"] per informazioni sui browser supportati.

. Selezionare `OK` quando viene visualizzata la finestra di dialogo.
+

NOTE: Viene visualizzata una nuova scheda. Attivare le finestre a comparsa sul browser se sono bloccate.

. Accettare l'informativa sulla privacy per l'URL. Viene visualizzato il seguente messaggio: `SMB agent is ready to use. Please refresh the analytics page`
. Visualizzare l'agente SMB nella scheda Agenti tornando alla scheda originale che ospita la GUI XCP file Analytics e aggiornando la pagina.




== Upgrade di file Analytics per PMI

Per aggiornare il file Analytics esistente per SMB, attenersi alla seguente procedura.

. Prima di eseguire file Analytics, verificare che anche il server Linux su cui è in esecuzione file Analytics sia aggiornato e che il servizio sia in esecuzione.
. In Windows, arrestare il servizio XCP esistente immettendo `CTRL-C` sulla riga di comando.
. Sostituire `xcp.exe` con l'ultimo binario.
. Andare sul computer Windows ed eseguire `xcp listen` Per configurare XCP file Analytics per SMB. Tenere il finestrino aperto per eseguire continuamente il servizio.
. Avviare file Analytics su un browser supportato: `\https://<ip address of linux>/xcp`
+
Fare riferimento a. link:xcp-install-xcp-smb.html["Installare XCP SMB"] per informazioni sui browser supportati.

. Selezionare *OK* quando viene visualizzata la finestra di dialogo.
+

NOTE: Viene visualizzata una nuova scheda. Attivare le finestre a comparsa sul browser se sono bloccate.

. Accettare l'informativa sulla privacy per l'URL. Viene visualizzato il seguente messaggio: `SMB agent is ready to use. Please refresh the analytics page`
. Visualizzare l'agente SMB nella scheda Agenti tornando alla scheda originale che ospita la GUI XCP file Analytics e aggiornando la pagina.

