---
sidebar: sidebar 
permalink: xcp-migrate-data.html 
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify 
summary: Migrare i dati 
---
= Migrare i dati NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver pianificato la migrazione con `show` e. `scan` , puoi migrare i dati NFS.



== Copia

Il `copy` Il comando esegue la scansione e copia dell'intera struttura della directory di origine in un'esportazione NFSv3 di destinazione. Il `copy` il comando richiede la presenza di percorsi di origine e destinazione come variabili. Al termine dell'operazione di copia vengono visualizzati i dati relativi a file sottoposti a scansione e copiati, velocità/velocità e tempo trascorso.

*Esempio:*

[listing]
----
xcp copy -newid <id> src_server:/src_export dst_server:/dst_export
----
*Esempio di percorso POSIX:*

[listing]
----
xcp copy -newid <id> file:///mnt/source file:///mnt/dest
----
Eseguire `xcp help copy` per ulteriori dettagli.



== Riprendi

Il `resume` command riavvia un'operazione di copia precedentemente interrotta specificando il nome o il numero dell'indice del catalogo. Il nome o il numero dell'indice del catalogo dell'operazione di copia precedente viene memorizzato in `<catalog path>:/catalog/indexes` directory.

*Esempio:*

[listing]
----
xcp resume [options] -id <id used for copy>
----
Eseguire `xcp help resume` per ulteriori dettagli.



== Sincronizza

Il `sync` Il comando esegue la scansione delle modifiche e delle modifiche apportate in una directory NFS di origine utilizzando un nome di tag di indice del catalogo o il numero di un'operazione di copia precedente. Le modifiche incrementali di origine vengono copiate e applicate alla directory di destinazione. I vecchi numeri di indice del catalogo vengono sostituiti con uno nuovo [.underline] dopo l'operazione di sincronizzazione n..

*Esempio:*

[listing]
----
xcp sync [options] -id <id used for copy>
----
Eseguire `xcp help sync` per ulteriori dettagli.



== Verificare

Il `verify` command utilizza un confronto completo dei dati byte per byte tra le directory di origine e di destinazione dopo l'operazione di copia senza utilizzare un numero di indice del catalogo. Il comando verifica i tempi di modifica e altri attributi di file o directory, incluse le autorizzazioni. Il comando legge anche i file su entrambi i lati e confronta i dati.

*Esempio:*

[listing]
----
xcp verify src_server:/src_export dst_server:/dst_export
----
*Esempio di percorso POSIX:*

[listing]
----
xcp verify file:///mnt/source file:///mnt/dest
----
Eseguire `xcp help verify` per ulteriori dettagli.



== ISync

Il `isync` comando confronta l'origine e la destinazione e sincronizza le differenze sulla destinazione senza utilizzare l'indice del catalogo.

*Esempio*

[listing]
----
xcp isync <source_ip_address>:/src <destination_ip_address>:/dest

----
È possibile utilizzare `isync` con `estimate` opzione per stimare il tempo necessario per `isync` per sincronizzare le modifiche incrementali. Il `-id` parametro specifica il nome di catalogo di un'operazione di copia precedente.


NOTE: Se si modifica più del 25% delle dimensioni del set di dati utilizzato, il `isync estimate` il comando potrebbe non visualizzare i risultati previsti.

*Esempio*

[listing]
----
xcp isync estimate -id <name>
----
Eseguire `xcp help isync` per ulteriori dettagli.
