---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: Installare o aggiornare file Analytics per NFS 
---
= Installare file Analytics per NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installare o aggiornare file Analytics per NFS.

.A proposito di questa attività
Per i requisiti di sistema per NFS, consulta link:xcp-install-xcp-nfs.html["Installare XCP NFS"].

Il `configure.sh` Script installa XCP file Analytics su un computer host Red Hat Enterprise Linux (RHEL). Come parte dell'installazione, lo script installa Postgres Database, Apache HTTPD server e altri pacchetti richiesti sulla macchina Linux host. Per informazioni su specifiche versioni RHEL supportate, fare riferimento alla link:https://mysupport.netapp.com/matrix/["IMT"^]. È possibile modificare o eseguire l'aggiornamento a una versione più recente in base alle necessità e attenersi alle linee guida sulla sicurezza. Per ulteriori informazioni su `configure.sh` script, esegui `./configure.sh -h` sulla riga di comando.

.Prima di iniziare
* Se sono in esecuzione operazioni XCP, NetApp consiglia di completare le operazioni prima di avviare la configurazione.
* La macchina Linux deve essere connessa al server di repository Yum o a Internet.
* Se sulla macchina Linux è configurato un firewall, è necessario modificare le impostazioni del firewall per abilitare la porta 5030, utilizzata dal servizio XCP.


.Fasi
. Installare o aggiornare file Analytics per NFS.
+
[role="tabbed-block"]
====
.Installare file Analytics
--
.. Passare a. `xcp` ed eseguire `./configure.sh` script.
+
Se l'installazione ha esito positivo, viene visualizzato il seguente messaggio:

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
+

NOTE: È possibile utilizzare questo nome utente e la password per accedere alla GUI di file Analytics.



--
.Aggiornamento di file Analytics
--
.. Passare a. `xcp` cartella ed esecuzione `./configure.sh -f`.
.. Quando richiesto, immettere `y` per pulire e riconfigurare il sistema.
+
Una volta approvato, lo script cancella la configurazione esistente e riconfigura il sistema.

+
Se l'operazione ha esito positivo, viene visualizzato il seguente messaggio:

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----


--
====
. Avviare file Analytics in un browser supportato: *\https://<ip address of linux>/xcp*.
+
Fare riferimento a. link:xcp-install-xcp-nfs.html["Installare XCP NFS"] per informazioni sui browser supportati.


