---
sidebar: sidebar 
permalink: xcp-troubleshoot-xcp-smb-errors.html 
keywords: netapp, xcp, troubleshoot, troubleshooting, smb, 
summary: Risoluzione dei problemi relativi agli errori SMB di XCP 
---
= Risolvere gli errori SMB XCP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esaminare le soluzioni per risolvere il problema.

|===
| Problema | Soluzione 


 a| 
I comandi XCP non mostrano i risultati previsti quando viene utilizzato un percorso di giunzione nell'origine o nella destinazione.
 a| 
Utilizzare un percorso di condivisione SMB invece di un percorso di giunzione quando si eseguono i comandi XCP.



 a| 
Un errore di traceback può verificarsi se l'origine, la destinazione o entrambi sono una giunzione senza directory e una licenza online viene utilizzata nella migrazione. In questo caso, lo stato del comando XCP è `PASSED` ma alla fine dell'output della console viene restituito il seguente errore:

[listing]
----
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "xcp\stats.py", line 214, in call_home
  File "xcp\histograms.py", line 387, in calculate_averages
ZeroDivisionError: division by zero
----| Utilizzare una licenza offline invece di una licenza online. 


| `xcp: ERROR`: Questa licenza è scaduta | Rinnovare o ottenere la nuova licenza XCP da link:https://xcp.netapp.com/["Sito XCP"^]. 


| Questa copia non è concessa in licenza | Ottenere il file di licenza XCP appropriato. Copiare la licenza XCP su `c:\netapp\xcp` Sull'host XCP. Eseguire `xcp activate` per attivare la licenza 


| `xcp: ERROR`: XCP non attivato, eseguire prima "Activate" | Scaricare la licenza XCP dal link:https://xcp.netapp.com/["Sito XCP"^]. Copiare il file sull'host del client XCP Linux all'indirizzo `c:\netapp\xcp` Sull'host XCP. Eseguire `xcp activate` per attivare la licenza. 


| `xcp: ERROR`File di licenza C: Licenza NetApp non trovata | Registrarsi per la licenza XCP su link:https://xcp.netapp.com/["Sito XCP"^]. Scaricare e copiare il file di licenza in `C:\NetApp\XCP\` Sull'host client XCP Windows. 


| Errore di scansione xcp: Impossibile trovare il nome di rete | Eseguire nuovamente il comando con il nome di condivisione corretto 


| Errore copia xcp: ERRORE durante il recupero dell'entità di protezione fallback messaggio di errore registrato nel file xcp.log:
`pywintypes.error: (1722, 'LookupAccountName', 'The RPC server is unavailable.')` | Aggiungere la casella di destinazione nel file hosts (`C:\Windows\System32\drivers\etc\hosts`). La casella di destinazione dello storage NetApp deve essere nel formato seguente:
`<data vserver data interface ip>` 1 o più spazi vuoti `<cifs server name>` 


| `xcp copy: ERROR` Impossibile ottenere l'entità di protezione fallback (inserire la casella di destinazione dopo l'aggiunta nei file host) errore di accesso al file xcp.log:
`'No mapping between account names and security IDs was done'` | L'utente/gruppo di fallback non esiste nel sistema di destinazione (casella di destinazione) o nella directory attiva. Eseguire nuovamente il comando con le opzioni utente/gruppo di fallback corrette 


| `xcp copy: ERROR` Impossibile ottenere l'entità di protezione fallback (inserire la casella di destinazione dopo l'aggiunta nei file host) errore di accesso al file xcp.log:
`pywintypes.error: (87, 'LookupAccountName', 'The parameter is incorrect.')` | Parametro errato per l'opzione utente/gruppo fallback. Eseguire nuovamente il comando con la sintassi corretta per le opzioni utente/gruppo di fallback 


| `xcp copy` Con migrazione ACL

Messaggio di errore registrato nel file xcp.log:
`pywintypes.error`: `(1314, 'GetNamedSecurityInfo', 'A required privilege is not held by the client.')` | Problema relativo ai descrittori di protezione, poiché l'account utente della migrazione dispone solo dei privilegi necessari per consentire a XCP di recuperare il proprietario, il gruppo e il DACL. Non è in grado di recuperare il SACL.
Aggiungere l'account utente per la migrazione al criterio "Gestisci registro di controllo e protezione" in Active Directory.
Riferimento: link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn221953%28v%3Dws.11%29["Gestire il registro di controllo e di sicurezza"^] 
|===